### ISSUE TITLE
Upload datasets on face anti-spoofing/liveness detection to Dropbox / Google drive

### ISSUE THREAD

**Issue by codonna9** [ZhaoJ9014/face.evoLVe.PyTorch#104]
I can't download these datasets from Baidu. If any of you downloaded them already, can you guys share them in Dropbox or Google drive? Many thanks in advance.

**Comment by ZhaoJ9014** [comment]
Hi, we have updated the links, thanks.

**Comment by jaydeep-sndk** [comment]
I am not able to access the link can you please as if it expired?

**Comment by sanjay7178** [comment]
can i have the dataset links please , I;m working  right now on live anti spoof detection model
