### ISSUE TITLE
How to convert the pre-model ir-50 to the onnx model of OpenCV DNN?

### ISSUE THREAD

**Issue by hipitt** [ZhaoJ9014/face.evoLVe.PyTorch#105]
As shown in the title

In short, how to use backbone_ir50_xxxx.pth in Opencv DNN,
Would you please provide an example code?
@ZhaoJ9014 @insightcs

**Comment by Pradhunmya** [comment]
Hello @hipitt,
were you able to get the solution for this, I need the same thing, convert it to ONNX and wants to run with opencv dnn?

**Comment by RamatovInomjon** [comment]
https://deci.ai/blog/how-to-convert-a-pytorch-model-to-onnx/
