### ISSUE TITLE
Unable to Download IR-152

### ISSUE THREAD

**Issue by turnersr** [ZhaoJ9014/face.evoLVe.PyTorch#108]
I am currently unable to download the IR-152 model because of the Baidu Link inaccessible from my location. Would it be possible to please upload the model files on to Google Drive or DropBox? 

Thank you!

**Comment by kormalev** [comment]
https://mega.nz/#F!EZsnEbbJ!qp4nVBBRKnAWYzyoiMfXQA

**Comment by ZhaoJ9014** [comment]
Hi, we have updated the links, thanks.
