### ISSUE TITLE
File on Baidu Drive has expired

### ISSUE THREAD

**Issue by wangliwei-intel** [ZhaoJ9014/face.evoLVe.PyTorch#109]
Hi, Jian,
Thanks for your great work.
I'm reading and trying your code, but this file on Baidu Drive has expired:
https://pan.baidu.com/s/1xh073sKX3IYp9xPm9S6F5Q

Could you please renew it or give another link on Google Drive?
Thanks a lot.

B. R.
Liwei

**Comment by ZhaoJ9014** [comment]
Hi, we have updated the links, thanks.
