### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by DecentMakeover** [ZhaoJ9014/face.evoLVe.PyTorch#11]
I wanted to perform face verification, correct me if i'm wrong, but most of the recognition models are trained on a million images or so, 

I was thinking if i could combine most of the open-source datasets like 1millionceleb, facesemore, lfw etc, and train the network, would that give me a better face embedding?

What do you think?

Thanks in advance.

**Comment by ZhaoJ9014** [comment]
Thank you for your question. Yes, surely you can if you have the name list of each database you want to merge, otherwise there may exist overlapping parts in your merged version, which may confuse your network during classifying these subjects.
