### ISSUE TITLE
Baidu drive not accessible

### ISSUE THREAD

**Issue by SourcM** [ZhaoJ9014/face.evoLVe.PyTorch#110]
Please can you place the IR152 checkpoints on google drive? basically baidu drive is not accessible.
Thanks

**Comment by kormalev** [comment]
https://mega.nz/#F!EZsnEbbJ!qp4nVBBRKnAWYzyoiMfXQA

**Comment by ZhaoJ9014** [comment]
Hi, we have updated the links, thanks.

**Comment by MyraBaba** [comment]
@ZhaoJ9014 
how can we download r152 model ? Baidu not accessible from EU
any other link that works?
Best
