### ISSUE TITLE
how can i get the pwd of the zip file ?

### ISSUE THREAD

**Issue by Eleanor456** [ZhaoJ9014/face.evoLVe.PyTorch#112]
When I unzip the download the CASIA-SURF dataset, it needs to input the pwd of the zip file, how can I get it.

**Comment by ZhaoJ9014** [comment]
> When I unzip the download the CASIA-SURF dataset, it needs to input the pwd of the zip file, how can I get it.

Hi, we have included the pw in the Download Link column. Please have a check. (PW: izb3)

**Comment by Eleanor456** [comment]
It doesn’t work.
The pwd is not used to extract the file from Baidu Driver, but used to unzip the training set and the valid set from the download files.


Thank you for response.








------------------ Original ------------------
