### ISSUE TITLE
lfw align 112*112 data issue

### ISSUE THREAD

**Issue by DecentMakeover** [ZhaoJ9014/face.evoLVe.PyTorch#12]
I think there is some problem with lfw 112*112 align zip in google drive , i'm not able to extract it

**Comment by ZhaoJ9014** [comment]
Thank you for your question. I have checked the link and did not find any problem. As explained by the "Remark" in Sec. Data Zoo, after unzip, you can get image data & pair ground truths from AgeDB, CFP, LFW and VGGFace2_FP align_112x112 versions with:
import numpy as np
import bcolz
import os

def get_pair(root, name):
    carray = bcolz.carray(rootdir = os.path.join(root, name), mode='r')
    issame = np.load('{}/{}_list.npy'.format(root, name))
    return carray, issame

def get_data(data_root):
    agedb_30, agedb_30_issame = get_pair(data_root, 'agedb_30')
    cfp_fp, cfp_fp_issame = get_pair(data_root, 'cfp_fp')
    lfw, lfw_issame = get_pair(data_root, 'lfw')
    vgg2_fp, vgg2_fp_issame = get_pair(data_root, 'vgg2_fp')
    return agedb_30, cfp_fp, lfw, vgg2_fp, agedb_30_issame, cfp_fp_issame, lfw_issame, vgg2_fp_issame

agedb_30, cfp_fp, lfw, vgg2_fp, agedb_30_issame, cfp_fp_issame, lfw_issame, vgg2_fp_issame = get_data(DATA_ROOT)

**Comment by andeyeluguo** [comment]
I can not unzip too.....

**Comment by ZhaoJ9014** [comment]
Hi, we have updated lfw_align_112 data, please have a check. Thx!

**Comment by andeyeluguo** [comment]
it still prompts that it is a broken file...also,it has no jpg file

**Comment by ZhaoJ9014** [comment]
Now it works:)
As explained by the "Remark" in Sec. Data Zoo, after unzip, you can get image data & pair ground truths from AgeDB, CFP, LFW and VGGFace2_FP align_112x112 versions with:
import numpy as np
import bcolz
import os

def get_pair(root, name):
carray = bcolz.carray(rootdir = os.path.join(root, name), mode='r')
issame = np.load('{}/{}_list.npy'.format(root, name))
return carray, issame

def get_data(data_root):
agedb_30, agedb_30_issame = get_pair(data_root, 'agedb_30')
cfp_fp, cfp_fp_issame = get_pair(data_root, 'cfp_fp')
lfw, lfw_issame = get_pair(data_root, 'lfw')
vgg2_fp, vgg2_fp_issame = get_pair(data_root, 'vgg2_fp')
return agedb_30, cfp_fp, lfw, vgg2_fp, agedb_30_issame, cfp_fp_issame, lfw_issame, vgg2_fp_issame

agedb_30, cfp_fp, lfw, vgg2_fp, agedb_30_issame, cfp_fp_issame, lfw_issame, vgg2_fp_issame = get_data(DATA_ROOT)

**Comment by vlad3996** [comment]
@ZhaoJ9014 I can not unzip [CPLFW](https://drive.google.com/file/d/1DJ8VYzc56GVXsWJQIj722yxlmaKV63_8/view?usp=sharing) and [CFP](https://drive.google.com/file/d/1DJ8VYzc56GVXsWJQIj722yxlmaKV63_8/view?usp=sharing) datasets.  
_End-of-central-directory signature not found_ error.
