### ISSUE TITLE
Whats the password for CASIA-SURF(RAW)?

### ISSUE THREAD

**Issue by Coderx7** [ZhaoJ9014/face.evoLVe.PyTorch#128]
Hi, thank you very much for your great contribution. 
I have downloaded the CASIA-SURF dataset, However, upon extracting it, it requires a password! I tried `izb3` which is given for the Baidu drive, but that doesnt work. 
So I'd really apprecaite it if you could kindly share with us the password for extraction? 
Thanks a lot

**Comment by neoludd8** [comment]
How did you manage to download the CASIA-SURF dataset? The Baidu Drive links no longer work for me!

**Comment by Coderx7** [comment]
@neoludd8  what do you mean it doesnt work for you? I just clicked on it and the link is OK/valid. 
I downloaded it around 7/8 months ago I only got the chance to look at it now though and I found it needs a second password for the actual extraction!

**Comment by neoludd8** [comment]
@Coderx7 do these links still work for you to this day? whenever i open one of them i get a 404 error message.

**Comment by Coderx7** [comment]
The links fine here it is again : https://pan.baidu.com/s/1dTGo9xcdTuK54RBgBWJNQg 

maybe you just get part of it. and thats why you face 404. it may be becasue of the firewall or censorship (your IP maybe blocked, etc) try using a vpn for example and see if that helps. (you can use cybeghost extension for chrome and firefox as well which works great)

**Comment by neoludd8** [comment]
@Coderx7 yeah it turned out to be an IP thing, thank you for the suggestion. If i had any luck with the password i'll let you know.

**Comment by Coderx7** [comment]
@neoludd8 Thanks a lot really appreciate it.

**Comment by Coderx7** [comment]
Found it here : 
https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/issues/97
passwords: 
**train.zip**: casia-cbsr-train-29266
**valid.zip**: casia-cbsr-valid-9608

**Comment by mike07026** [comment]
@Coderx7 Do you hava SiW dataset for anti-spoofing ?

**Comment by Coderx7** [comment]
@mike07026 nope not yet!

**Comment by whoisltd** [comment]
@Coderx7 this data was remove on baidu. Does you have another link?
