### ISSUE TITLE
Detail about the folder structure

### ISSUE THREAD

**Issue by DecentMakeover** [ZhaoJ9014/face.evoLVe.PyTorch#13]
Hi

What should be the training data folder structure?

should it be $rootfolder/data/train, $rootfolder/data/val,  $rootfolder/data/test 

or  $rootfolder/data/imgs 

Thanks in advance.

**Comment by ZhaoJ9014** [comment]
Thank you for your question. Actually, you can custom your own root of training data by modifying the Line 8 of config.py and Line 70 of train.py. In our case, the root of training data is "/media/pc/6T/jasonjzhao/data/faces_emore/imgs".
