### ISSUE TITLE
Will it work in windows or what I need to run it on windows

### ISSUE THREAD

**Issue by RUPESHKUMARPALLAI** [ZhaoJ9014/face.evoLVe.PyTorch#158]
Will it work in windows also

**Comment by perfectZh** [comment]
Currently, this project only supports Linux or macOS.
Maybe you could try following suggestions.
https://www.howtogeek.com/170870/5-ways-to-run-linux-software-on-windows/

**Comment by RUPESHKUMARPALLAI** [comment]
Ok I am trying to get it work in windows
