### ISSUE TITLE
what's the difference of accuracy_cfp_ff and accuracy_cfp_fp?

### ISSUE THREAD

**Issue by andeyeluguo** [ZhaoJ9014/face.evoLVe.PyTorch#19]
I only found the cfp dataset ,don't know the difference of the cfp_ff and cfg_fp

**Comment by ZhaoJ9014** [comment]
Thank you for your question. CFP has two settings for evaluation, i.e., frontal to frontal verification (CFP_FF) and frontal to profile verification (CFP_FP). You can refer to their official website (http://www.cfpw.io/) for details.
