### ISSUE TITLE
Asking for meta and sizes

### ISSUE THREAD

**Issue by DecentMakeover** [ZhaoJ9014/face.evoLVe.PyTorch#20]
i am trying to train the network on lfw, 

my folder structure looks like 

`$RootFolder/data/train`, `$RootFolder/data/val`, `$RootFolder/data/test`

but when i run `train.py` , i get 

`FileNotFoundError: [Errno 2] No such file or directory: '/media/ryan/shakira/face.evoLVe.PyTorch/data/lfw/meta/sizes'`

Am i missing something?

Thanks in advance.

**Comment by ZhaoJ9014** [comment]
Hi, I have checked the released lfw data, and did not find any problem. The error shows that you may have a wrong path, please re-check it to solve the problem. Or you can use other dataset for debug first.

**Comment by sankovalev** [comment]
> i am trying to train the network on lfw,
> 
> my folder structure looks like
> 
> `$RootFolder/data/train`, `$RootFolder/data/val`, `$RootFolder/data/test`
> 
> but when i run `train.py` , i get
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/media/ryan/shakira/face.evoLVe.PyTorch/data/lfw/meta/sizes'`
> 
> Am i missing something?
> 
> Thanks in advance.

You should download the dataset from here: https://github.com/TreB1eN/InsightFace_Pytorch#323-prepare-dataset--for-training

**Comment by Arctanxy** [comment]
I met the same problem, there's no meta/sizes in my lfw dataset.

**Comment by JerryHanZD** [comment]
Anyone selved this problem? I met the same one.

**Comment by iamadog3333** [comment]
When train on LFW. I also met the problem. 

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/zhangqiang/Downloads/gitProject/face.evoLVe.PyTorch-master/data\\lfw\\meta\\sizes'

**Comment by iamadog3333** [comment]
does the lfw dataset have the meta ? I can not unzip your lfw_alighed_112 on baidu yunpan. also ,when I open it with rar(note just open), it's name is casia???

This repo use the data prepared like this. It will solve the problem.
https://github.com/TreB1eN/InsightFace_Pytorch#323-prepare-dataset--for-training

**Comment by borhanreo** [comment]
I am facing the same problem. Anyone solved this problem?

**Comment by iamadog3333** [comment]
This repo use the data prepared like this. It will solve the problem.
https://github.com/TreB1eN/InsightFace_Pytorch#323-prepare-dataset--for-training
