### ISSUE TITLE
If I use a pretrained model do I need to train to recognize people?

### ISSUE THREAD

**Issue by educob** [ZhaoJ9014/face.evoLVe.PyTorch#22]
Hi.

What I have understood is that a trained model will assign a vector to each face. With each vector I find in the database if that person is already registered (distance between vector <= 0.99).
Is this wrong? Do I have to train the network with the faces of people I want it to recognize?

I have read several times the documentation but I don't know how to assign a vector to a face. Where ca nI find that code?

Thanks.

**Comment by ZhaoJ9014** [comment]
Hi, thank you for your question. Actually, what you need is the Feature extraction API (extract features from pre-trained models). We have two versions for you: ./util/extract_feature_v1.py (implemented with PyTorch build-in functions) and ./util/extract_feature_v2.py (implemented with OpenCV).

**Comment by educob** [comment]
Thanks for your help.

What would be the model to load in the backbone?

**Comment by ZhaoJ9014** [comment]
> Thanks for your help.
> 
> What would be the model to load in the backbone?

Hi, the model to load is only the backbone for feature extraction. You don't need a valid path for head, since it will not be used.
