### ISSUE TITLE
Cannot unzip ms1m_align_112.zip

### ISSUE THREAD

**Issue by lymanblue** [ZhaoJ9014/face.evoLVe.PyTorch#25]
Hi~

We downloaded the dataset from Google Drive.
But we cannot unzip the file ms1m_align_112.zip (>25GB).

Could you check this issue?
If possible, would you provide the md5 checksum of the dataset (or all the dataset)?
Thank you.

**Comment by ZhaoJ9014** [comment]
Sure. We will check it and reply you soon.

**Comment by ZhaoJ9014** [comment]
> Hi~
> 
> We downloaded the dataset from Google Drive.
> But we cannot unzip the file ms1m_align_112.zip (>25GB).
> 
> Could you check this issue?
> If possible, would you provide the md5 checksum of the dataset (or all the dataset)?
> Thank you.

Hi, we have updated the data. Please have a check:)

**Comment by lymanblue** [comment]
Thank you very much!
We can upzip the dataset now.
