### ISSUE TITLE
There is no pre-trained model of HEAD part in Model Zoo

### ISSUE THREAD

**Issue by lymanblue** [ZhaoJ9014/face.evoLVe.PyTorch#28]
Hi~

The model zoo only provides the BACKBONE pre-trained model.
Would the pre-trained model of HEAD part be released?

Thank you.

**Comment by ZhaoJ9014** [comment]
Hi, yes, we will also release the pre-trained head part for the next model:)

**Comment by njuaplusplus** [comment]
Hi Professor Zhao,

I wonder when the pre-trained head part will be released. Thank you.


Best,
Shengwei
