### ISSUE TITLE
Cannot ues the aligned CFP

### ISSUE THREAD

**Issue by xiaosuzhang** [ZhaoJ9014/face.evoLVe.PyTorch#29]
Could you please upload the aligned CFP datasets? It cannot use

**Comment by ZhaoJ9014** [comment]
We had a check and found some problems with the zip file. Will update it soon:)

**Comment by ZhaoJ9014** [comment]
> Could you please upload the aligned CFP datasets? It cannot use

Updated, please have a check. Thx.
