### ISSUE TITLE
How to use the extract_feature_v2.py to complish face compare？

### ISSUE THREAD

**Issue by xiaosuzhang** [ZhaoJ9014/face.evoLVe.PyTorch#31]
When i use the extract_feature_v2.py to extract the face feature to compare the faces which are in CFP-datases similarity，but the similarity between faces is too low. How should to improve the similarity?How to compute the distance the features?

**Comment by ZhaoJ9014** [comment]
Hi, thank you for your question. Please refer to Line 232-235 of train.py for evaluation on CFP.

**Comment by xiaosuzhang** [comment]
Thanks! But i only calculator the similarity between the two  faces, and the confidence is too slow. How should i do?
