### ISSUE TITLE
How to transform the L2-norm distance to the similarity?

### ISSUE THREAD

**Issue by xiaosuzhang** [ZhaoJ9014/face.evoLVe.PyTorch#33]
Sorry to interrupt again. I used np.linalg.norm to compute the distance between two faces. How should i use the l2-norm distance to get the similarity between the face images? Thanks!!

**Comment by ZhaoJ9014** [comment]
> Sorry to interrupt again. I used np.linalg.norm to compute the distance between two faces. How should i use the l2-norm distance to get the similarity between the face images? Thanks!!

Hi, please refer to ./util/verification.py Line 52-53. Thx.
