### ISSUE TITLE
I met a problem when I want to load the pretrained_model on Baidu Driver

### ISSUE THREAD

**Issue by foolishhmy** [ZhaoJ9014/face.evoLVe.PyTorch#34]
My code is as follows:
backbone = IR_50((112, 112))
backbone.load_state_dict(torch.load(model_root))
the pretrainded model is backbone_ir50_ms1m_epoch120.pth
and I met a sizematch problem
Please tell me how to write the right load code, thank you so much!

**Comment by ZhaoJ9014** [comment]
> My code is as follows:
> backbone = IR_50((112, 112))
> backbone.load_state_dict(torch.load(model_root))
> the pretrainded model is backbone_ir50_ms1m_epoch120.pth
> and I met a sizematch problem
> Please tell me how to write the right load code, thank you so much!

Hi, thank you for your question. As indicated in train.py, you can load the model with: BACKBONE.load_state_dict(torch.load(BACKBONE_RESUME_ROOT))
HEAD.load_state_dict(torch.load(HEAD_RESUME_ROOT))

**Comment by foolishhmy** [comment]
> > My code is as follows:
> > backbone = IR_50((112, 112))
> > backbone.load_state_dict(torch.load(model_root))
> > the pretrainded model is backbone_ir50_ms1m_epoch120.pth
> > and I met a sizematch problem
> > Please tell me how to write the right load code, thank you so much!
> 
> Hi, thank you for your question. As indicated in train.py, you can load the model with: BACKBONE.load_state_dict(torch.load(BACKBONE_RESUME_ROOT))
> HEAD.load_state_dict(torch.load(HEAD_RESUME_ROOT))

I found that code on Baidu Driver is different from code on github, when I copy the code from Baidu Driver, it works...

**Comment by ZhaoJ9014** [comment]
> > > My code is as follows:
> > > backbone = IR_50((112, 112))
> > > backbone.load_state_dict(torch.load(model_root))
> > > the pretrainded model is backbone_ir50_ms1m_epoch120.pth
> > > and I met a sizematch problem
> > > Please tell me how to write the right load code, thank you so much!
> > 
> > 
> > Hi, thank you for your question. As indicated in train.py, you can load the model with: BACKBONE.load_state_dict(torch.load(BACKBONE_RESUME_ROOT))
> > HEAD.load_state_dict(torch.load(HEAD_RESUME_ROOT))
> 
> I found that code on Baidu Driver is different from code on github, when I copy the code from Baidu Driver, it works...

Hi, yes. We slightly updated the backbone code. We have released the pre-trained model along with corresponding structure definition file.
