### ISSUE TITLE
question about retrain the model

### ISSUE THREAD

**Issue by youngking0727** [ZhaoJ9014/face.evoLVe.PyTorch#38]
Thank you very much for your high performance repo!
I want to improve the recognition rate on my dataset, so I use the “backbone_ir50_asia.pth”  you have released as the pretrain backbone model to retrain it, I update all the parameter of the backbone, but the val acc of calfw is only 56% even after 50 epochs. So I decide to only retrain the parameter of fc1 and fc2 of the backboned, do you think it will be used? 
Can you give me some precious advice about how to improve the model's recognition rate on real scene  and how should i do to finetune the pretrian backbone model?
thanks, good wishes for you!

**Comment by ZhaoJ9014** [comment]
> Thank you very much for your high performance repo!
> I want to improve the recognition rate on my dataset, so I use the “backbone_ir50_asia.pth” you have released as the pretrain backbone model to retrain it, I update all the parameter of the backbone, but the val acc of calfw is only 56% even after 50 epochs. So I decide to only retrain the parameter of fc1 and fc2 of the backboned, do you think it will be used?
> Can you give me some precious advice about how to improve the model's recognition rate on real scene and how should i do to finetune the pretrian backbone model?
> thanks, good wishes for you!

Thank you for your question. May I know your LR during fine-tuning?

**Comment by youngking0727** [comment]
> > Thank you very much for your high performance repo!
> > I want to improve the recognition rate on my dataset, so I use the “backbone_ir50_asia.pth” you have released as the pretrain backbone model to retrain it, I update all the parameter of the backbone, but the val acc of calfw is only 56% even after 50 epochs. So I decide to only retrain the parameter of fc1 and fc2 of the backboned, do you think it will be used?
> > Can you give me some precious advice about how to improve the model's recognition rate on real scene and how should i do to finetune the pretrian backbone model?
> > thanks, good wishes for you!
> 
> Thank you for your question. May I know your LR during fine-tuning?

I just start the training and don't change the LR in the config. the LR is 0.1 and epochs is 125. Now 60 epochs has ended. The training prec@1 is 94.7, training prec@5 is 96.8 and val acc of calfw is still 56%

**Comment by khoaLearnToCode** [comment]
@youngking0727 Can you tell me how to retrain on a custom dataset using only the backbone resume? Is it true that I must have both backbone and head checkpoint to retrain on a custom dataset? Thank you!
