### ISSUE TITLE
Center Crop or Face Aligned for the Embeddings ?

### ISSUE THREAD

**Issue by vdsprakash** [ZhaoJ9014/face.evoLVe.PyTorch#44]
Are you taking the center crop or Aligned face for producing the Embeddings.

**Comment by ZhaoJ9014** [comment]
> Are you taking the center crop or Aligned face for producing the Embeddings.

Hi, I use aligned faces by MTCNN (you can find the scripts in ./align).

**Comment by anguoyang** [comment]
sorry for re-open this, do you think RetinaFace will improve the accuracy than MTCNN?
@ZhaoJ9014

**Comment by tanya-suri** [comment]
@ZhaoJ9014 how to set the margin value for the face alignment,
