### ISSUE TITLE
Hi, thanks for the commit. When i am testing on my private images the model isn't performing good. i am getting an F-score of 52%

### ISSUE THREAD

**Issue by chpk** [ZhaoJ9014/face.evoLVe.PyTorch#45]

**Comment by ZhaoJ9014** [comment]
> _No description provided._

Hi, if all your data are correctly loaded and preprocessed, then you can try to finetune on your own data and see.

**Comment by chpk** [comment]
Hi thanks for yours fast response. I didn't get what's meant by  correctly loaded. I am using function from utils/extract_feature_v2.py. Please can you share your pre-processing techniques which are being implemented separately.

**Comment by ZhaoJ9014** [comment]
> Hi thanks for yours fast response. I didn't get what's meant by correctly loaded. I am using function from utils/extract_feature_v2.py. Please can you share your pre-processing techniques which are being implemented separately.

Hi, you can find the preprocessing details in Line 61-85 of train.py.
