### ISSUE TITLE
Testing on a single image without a data loader

### ISSUE THREAD

**Issue by QuantScientist** [ZhaoJ9014/face.evoLVe.PyTorch#53]
Dear Team,
Thank you so much for this great repo. 
Is there code somewhere for inference on a single image, without using a data loader? 

Thanks,

**Comment by ZhaoJ9014** [comment]
> Dear Team,
> Thank you so much for this great repo.
> Is there code somewhere for inference on a single image, without using a data loader?
> 
> Thanks,

Hi, thank you for your question. Please refer to ./util/extract_feature_v2.py
