### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by ZZH2950228** [ZhaoJ9014/face.evoLVe.PyTorch#56]
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    weights = make_weights_for_balanced_classes(dataset_train.imgs, len(dataset_train.classes))
  File "/home/zzh/桌面/face.evoLVe/face.evoLVe.PyTorch-master/util/utils.py", line 47, in make_weights_for_balanced_classes
    weight_per_class[i] = N / float(count[i])
ZeroDivisionError: float division by zero

**Comment by ZhaoJ9014** [comment]
> Traceback (most recent call last):
> File "train.py", line 73, in 
> weights = make_weights_for_balanced_classes(dataset_train.imgs, len(dataset_train.classes))
> File "/home/zzh/桌面/face.evoLVe/face.evoLVe.PyTorch-master/util/utils.py", line 47, in make_weights_for_balanced_classes
> weight_per_class[i] = N / float(count[i])
> ZeroDivisionError: float division by zero

Hi, It seems that there exist some problem with your training data, please follow the dataset organization as indicated in our repo. Please re-check your training data and related paths.
