### ISSUE TITLE
Can you publish data sets and models in Baidu cloud? Google hard disk downloads are all wrong, prompting too many people to download recently, has been blocked. Thank you

### ISSUE THREAD

**Issue by QQ2737499951** [ZhaoJ9014/face.evoLVe.PyTorch#63]
Can you publish data sets and models in Baidu cloud? Google hard disk downloads are all wrong, prompting too many people to download recently, has been blocked. Thank you

MS-Celeb-1M | Clean | 100,000 | 5,084,127 | - | - | Google Drive   https://drive.google.com/file/d/18FxgfXgKwuYzY3DmWJXNJuY51TPmC9yH/view?usp=sharing
-- | -- | -- | -- | -- | -- | --
MS-Celeb-1M | Align_112x112 | 85,742 | 5,822,653 | - | - | Google Drive

https://drive.google.com/file/d/1X202mvYe5tiXFhOx82z4rPiPogXD435i/view?usp=sharing

Vggface2 | Clean | 8,631 | 3,086,894 | - | - | Google Drive

https://drive.google.com/file/d/1jdZw6ZmB7JRK6RS6QP3YEr2sufJ5ibtO/view?usp=sharing

![QQ图片20190611215019](https://user-images.githubusercontent.com/33048209/59277912-989cba00-8c93-11e9-8782-88ddf8ae1e77.jpg)

**Comment by ZhaoJ9014** [comment]
Hi, for large datasets or models, we opt for google drive since baidu drive has limitation on the size of file per uploading. But for others, we have already provided both baidu drive and google drive links:)
