### ISSUE TITLE
how to generate eval data?

### ISSUE THREAD

**Issue by tugstugi** [ZhaoJ9014/face.evoLVe.PyTorch#66]
How do I generate an eval dataset for my images? The provided data seems to be not compatible with https://github.com/deepinsight/insightface/blob/master/recognition/data/build_eval_pack.py?

**Comment by ZhaoJ9014** [comment]
> How do I generate an eval dataset for my images? The provided data seems to be not compatible with https://github.com/deepinsight/insightface/blob/master/recognition/data/build_eval_pack.py?

Hi, this repo is actually different with InsightFace, pls refer our intro sec. To prepare your own data for evaluation, you can just follow the standard pytorch dataloader implementation.

**Comment by tugstugi** [comment]
@ZhaoJ9014 you answer was not really helpful, but I have found the answer myself. For other people who want to create a validation dataset:
* create a validation dataset with: https://github.com/deepinsight/insightface/blob/master/recognition/data/build_eval_pack.py
* convert to the bcolz format with https://github.com/TreB1eN/InsightFace_Pytorch/blob/master/prepare_data.py
* now you can use the method `get_pair/perform_val` to validate your dataset

**Comment by khoaLearnToCode** [comment]
@tugstugi Hi, I'm trying to create a validation dataset on my own, can you please give more details on how you created your own validation dataset? I already created a face image folder with the structure as described in the info sec, I already found the build_eval_pack.py from insightface repo although they removed it recently, but I still don't know how to create the validation dataset with the build_eval_pack.py like your mentioned. 
Please, any replies from you would be a big help!
