### ISSUE TITLE
Training Data - 65k links / directories limit ext4 

### ISSUE THREAD

**Issue by fmobrj** [ZhaoJ9014/face.evoLVe.PyTorch#67]
Hello Zhao,

The data structure for training results in more than 65k directories (one for each class). I am having problem in organizing the data for training, once Linux ext4 filesystem has a 65k limit for hardlinks. 

Are you using linux? How did you solve this limitation?

Thank you.

**Comment by ZhaoJ9014** [comment]
> Hello Zhao,
> 
> The data structure for training results in more than 65k directories (one for each class). I am having problem in organizing the data for training, once Linux ext4 filesystem has a 65k limit for hardlinks.
> 
> Are you using linux? How did you solve this limitation?
> 
> Thank you.

Hi, we are using Ubuntu 16.04 and did not meet with the above problem.
