### ISSUE TITLE
Testing of pretrained model on my private face verification dataset.

### ISSUE THREAD

**Issue by pp3993** [ZhaoJ9014/face.evoLVe.PyTorch#69]
Hi 
Thanks for the repository, I want to evaluate the performance of this model on my own private dataset before starting the training, But i could not found the script for testing the model on your own datasets. 
can you please reply to this query?

Thankyou!!

**Comment by ZhaoJ9014** [comment]
> Hi
> Thanks for the repository, I want to evaluate the performance of this model on my own private dataset before starting the training, But i could not found the script for testing the model on your own datasets.
> can you please reply to this query?
> 
> Thankyou!!

Hi, we have actually provided APIs for evaluation on any datasets. Please refer to Feature extraction API (extract features from pre-trained models) ./util/extract_feature_v1.py (implemented with PyTorch build-in functions) and ./util/extract_feature_v2.py (implemented with OpenCV), and Line #61-#85 & #226-#245 of train.py.
