### ISSUE TITLE
there are lot of errors in this git lib for example utlits.py there are extra  parenthesis.after solved nearly 50 problems i got stuck here

### ISSUE THREAD

**Issue by syedmustafa54** [ZhaoJ9014/face.evoLVe.PyTorch#7]
```
 python train.py
============================================================
Overall Configurations:
{'SEED': 1337, 'DATA_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/alogn_faces', 'MODEL_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/model', 'LOG_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/log', 'BACKBONE_RESUME_ROOT': './', 'HEAD_RESUME_ROOT': './', 'BACKBONE_NAME': 'IR_SE_50', 'HEAD_NAME': 'ArcFace', 'LOSS_NAME': 'Focal', 'INPUT_SIZE': [112, 112], 'RGB_MEAN': [0.5, 0.5, 0.5], 'RGB_STD': [0.5, 0.5, 0.5], 'EMBEDDING_SIZE': 512, 'BATCH_SIZE': 512, 'DROP_LAST': True, 'LR': 0.1, 'NUM_EPOCH': 125, 'WEIGHT_DECAY': 0.0005, 'MOMENTUM': 0.9, 'STAGES': [35, 65, 95], 'DEVICE': device(type='cuda', index=0), 'MULTI_GPU': True, 'GPU_ID': [0, 1, 2, 3], 'PIN_MEMORY': True, 'NUM_WORKERS': 0}
============================================================
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    weights = make_weights_for_balanced_classes(dataset_train.imgs, len(dataset_train.classes))
  File "/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/util/utils.py", line 47, in make_weights_for_balanced_classes
    weight_per_class[i] = N / float(count[i])
ZeroDivisionError: float division by zero
```

**Comment by ZhaoJ9014** [comment]
Hi, thank you for your question. We actually tested many times before we launch this repo here and we haven't found any issue till now.
For your questions, we recommend you to understand each function in the code first before actually run it. Please re-check your training data to see if every class subfolder have at least one valid image file in it. Please check the description in our face.evoLVe repo for details on data organization and so on. Thx!

**Comment by syedmustafa54** [comment]
Thanks for the soon response @ZhaoJ9014 please see [this is 1](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/util/utils.py#L196) [this is 2](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/util/utils.py#L207) may be I am wrong in trying this in a worng way but this are code errors please recheck it.
If react in positive way then I have more 5 errors that need to be changes in code. So Please Update this code

**Comment by ZhaoJ9014** [comment]
> Thanks for the soon response @ZhaoJ9014 please see [this is 1](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/util/utils.py#L196) [this is 2](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/util/utils.py#L207) may be I am wrong in trying this in a worng way but this are code errors please recheck it.
> If react in positive way then I have more 5 errors that need to be changes in code. So Please Update this code

Thank you for your pointing out. Sorry here we missed a "(" during pushing the updates, which should be "embeddings[idx:idx + batch_size] = l2_norm(backbone(ccropped.to(device))).cpu()". We have updated the code accordingly.

**Comment by syedmustafa54** [comment]
@ZhaoJ9014 there are indent errors on `face.evoLVe.PyTorch/head/metrics.py` 
line [146](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/head/metrics.py#L147) , [206](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/head/metrics.py#L206) ,[289](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/head/metrics.py#L289)
```
File "train.py", line 10, in <module>
    from head.metrics import ArcFace, CosFace, SphereFace, Am_softmax
  File "/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/head/metrics.py", line 147
    nn.init.xavier_uniform_(self.weight)
    ^
IndentationError: unexpected indent

```

My folder structure is 

```
-> face.evoLVe.PyTorch/data/
  ->/train/
  ->/
```
after running `python face_align.py -source_root './data/train' -dest_root './data/train_Aligned' -crop_size 112`


My folder structure is 

```
-> face.evoLVe.PyTorch/data/
  ->/train/
  ->/train_Aligned
```
after running this command `python remove_lowshot.py -root './data/train' -min_num 10` it has removed some folders which were having less than 10 images
I  created `buffer` folder inside that a `model` folder and `log` folder
here is my config file 
```
import torch


configurations = {
    1: dict(
        SEED = 1337, # random seed for reproduce results

        DATA_ROOT = '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data', # the parent root where your train/val/test data are stored
        MODEL_ROOT = '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/model', # the root to buffer your checkpoints
        LOG_ROOT = '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/log', # the root to log your train/val status
        BACKBONE_RESUME_ROOT = './', # the root to resume training from a saved checkpoint
        HEAD_RESUME_ROOT = './', # the root to resume training from a saved checkpoint

        BACKBONE_NAME = 'IR_SE_50', # support: ['ResNet_50', 'ResNet_101', 'ResNet_152', 'IR_50', 'IR_101', 'IR_152', 'IR_SE_50', 'IR_SE_101', 'IR_SE_152']
        HEAD_NAME = 'ArcFace', # support:  ['Softmax', 'ArcFace', 'CosFace', 'SphereFace', 'Am_softmax']
        LOSS_NAME = 'Focal', # support: ['Focal', 'Softmax']

        INPUT_SIZE = [112, 112], # support: [112, 112] and [224, 224]
        RGB_MEAN = [0.5, 0.5, 0.5], # for normalize inputs to [-1, 1]
        RGB_STD = [0.5, 0.5, 0.5],
        EMBEDDING_SIZE = 512, # feature dimension
        BATCH_SIZE = 512,
        DROP_LAST = True, # whether drop the last batch to ensure consistent batch_norm statistics
        LR = 0.1, # initial LR
        NUM_EPOCH = 125, # total epoch number (use the firt 1/25 epochs to warm up)
        WEIGHT_DECAY = 5e-4, # do not apply to batch_norm parameters
        MOMENTUM = 0.9,
        STAGES = [35, 65, 95], # epoch stages to decay learning rate

        DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu"),
        MULTI_GPU = True, # flag to use multiple GPUs; if you choose to train with single GPU, you should first run "export CUDA_VISILE_DEVICES=device_id" to specify the GPU card you want to use
        GPU_ID = [0, 1, 2, 3], # specify your GPU ids
        PIN_MEMORY = True,
        NUM_WORKERS = 0,
),
}

```
than i ran  python train.py I was getting this error 
```
 ============================================================
Overall Configurations:
{'SEED': 1337, 'DATA_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data', 'MODEL_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/model', 'LOG_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/log', 'BACKBONE_RESUME_ROOT': './', 'HEAD_RESUME_ROOT': './', 'BACKBONE_NAME': 'IR_SE_50', 'HEAD_NAME': 'ArcFace', 'LOSS_NAME': 'Focal', 'INPUT_SIZE': [112, 112], 'RGB_MEAN': [0.5, 0.5, 0.5], 'RGB_STD': [0.5, 0.5, 0.5], 'EMBEDDING_SIZE': 512, 'BATCH_SIZE': 512, 'DROP_LAST': True, 'LR': 0.1, 'NUM_EPOCH': 125, 'WEIGHT_DECAY': 0.0005, 'MOMENTUM': 0.9, 'STAGES': [35, 65, 95], 'DEVICE': device(type='cuda', index=0), 'MULTI_GPU': True, 'GPU_ID': [0, 1, 2, 3], 'PIN_MEMORY': True, 'NUM_WORKERS': 0}
============================================================
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    dataset_train = datasets.ImageFolder(os.path.join(DATA_ROOT, 'imgs'), train_transform)
  File "/home/mustafa/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 178, in __init__
    target_transform=target_transform)
  File "/home/mustafa/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 75, in __init__
    classes, class_to_idx = find_classes(root)
  File "/home/mustafa/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 23, in find_classes
    classes = [d for d in os.listdir(dir) if os.path.isdir(os.path.join(dir, d))]
FileNotFoundError: [Errno 2] No such file or directory: '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data/imgs'

```
Solved this by changing `    dataset_train = datasets.ImageFolder(os.path.join(DATA_ROOT, 'imgs'), train_transform)
` to `    dataset_train = datasets.ImageFolder(os.path.join(DATA_ROOT, 'train'), train_transform)
`
```
but again a new error :dancing_men: 
============================================================
Overall Configurations:
{'SEED': 1337, 'DATA_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data', 'MODEL_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/model', 'LOG_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/log', 'BACKBONE_RESUME_ROOT': './', 'HEAD_RESUME_ROOT': './', 'BACKBONE_NAME': 'IR_SE_50', 'HEAD_NAME': 'ArcFace', 'LOSS_NAME': 'Focal', 'INPUT_SIZE': [112, 112], 'RGB_MEAN': [0.5, 0.5, 0.5], 'RGB_STD': [0.5, 0.5, 0.5], 'EMBEDDING_SIZE': 512, 'BATCH_SIZE': 512, 'DROP_LAST': True, 'LR': 0.1, 'NUM_EPOCH': 125, 'WEIGHT_DECAY': 0.0005, 'MOMENTUM': 0.9, 'STAGES': [35, 65, 95], 'DEVICE': device(type='cuda', index=0), 'MULTI_GPU': True, 'GPU_ID': [0, 1, 2, 3], 'PIN_MEMORY': True, 'NUM_WORKERS': 0}
============================================================
/home/mustafa/anaconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py:115: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.weights = torch.tensor(weights, dtype=torch.double)
Number of Training Classes: 5749
Traceback (most recent call last):
  File "train.py", line 85, in <module>
    lfw, cfp_ff, cfp_fp, agedb, calfw, cplfw, vgg2_fp, lfw_issame, cfp_ff_issame, cfp_fp_issame, agedb_issame, calfw_issame, cplfw_issame, vgg2_fp_issame = get_val_data(DATA_ROOT)
  File "/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/util/utils.py", line 63, in get_val_data
    lfw, lfw_issame = get_val_pair(data_path, 'lfw')
  File "/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/util/utils.py", line 56, in get_val_pair
    carray = bcolz.carray(rootdir = os.path.join(path, name), mode = 'r')
  File "bcolz/carray_ext.pyx", line 1067, in bcolz.carray_ext.carray.__cinit__
  File "bcolz/carray_ext.pyx", line 1369, in bcolz.carray_ext.carray._read_meta
FileNotFoundError: [Errno 2] No such file or directory: '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data/lfw/meta/sizes'

```
I am using ifw data base and my train folde is just rename of ifw to train can you tell me what i am doing wrong :confused:

**Comment by ZhaoJ9014** [comment]
Hi, the error indicates that you may have a wrong path since "No such file or directory: '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data/lfw/meta/sizes'". Please re-check to see whether the path is correct or not. Thx.

**Comment by andeyeluguo** [comment]
does the lfw dataset have the meta ? I can not unzip your lfw_alighed_112 on baidu yunpan. also ,when I open it with rar(note just open), it's name is casia???

**Comment by sankovalev** [comment]
> does the lfw dataset have the meta ? I can not unzip your lfw_alighed_112 on baidu yunpan. also ,when I open it with rar(note just open), it's name is casia???

https://github.com/TreB1eN/InsightFace_Pytorch#323-prepare-dataset--for-training

**Comment by xz-smart** [comment]
> @ZhaoJ9014 there are indent errors on `face.evoLVe.PyTorch/head/metrics.py`
> line [146](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/head/metrics.py#L147) , [206](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/head/metrics.py#L206) ,[289](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/head/metrics.py#L289)
> 
> ```
> File "train.py", line 10, in <module>
>     from head.metrics import ArcFace, CosFace, SphereFace, Am_softmax
>   File "/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/head/metrics.py", line 147
>     nn.init.xavier_uniform_(self.weight)
>     ^
> IndentationError: unexpected indent
> ```
> 
> My folder structure is
> 
> ```
> -> face.evoLVe.PyTorch/data/
>   ->/train/
>   ->/
> ```
> 
> after running `python face_align.py -source_root './data/train' -dest_root './data/train_Aligned' -crop_size 112`
> 
> My folder structure is
> 
> ```
> -> face.evoLVe.PyTorch/data/
>   ->/train/
>   ->/train_Aligned
> ```
> 
> after running this command `python remove_lowshot.py -root './data/train' -min_num 10` it has removed some folders which were having less than 10 images
> I created `buffer` folder inside that a `model` folder and `log` folder
> here is my config file
> 
> ```
> import torch
> 
> 
> configurations = {
>     1: dict(
>         SEED = 1337, # random seed for reproduce results
> 
>         DATA_ROOT = '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data', # the parent root where your train/val/test data are stored
>         MODEL_ROOT = '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/model', # the root to buffer your checkpoints
>         LOG_ROOT = '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/log', # the root to log your train/val status
>         BACKBONE_RESUME_ROOT = './', # the root to resume training from a saved checkpoint
>         HEAD_RESUME_ROOT = './', # the root to resume training from a saved checkpoint
> 
>         BACKBONE_NAME = 'IR_SE_50', # support: ['ResNet_50', 'ResNet_101', 'ResNet_152', 'IR_50', 'IR_101', 'IR_152', 'IR_SE_50', 'IR_SE_101', 'IR_SE_152']
>         HEAD_NAME = 'ArcFace', # support:  ['Softmax', 'ArcFace', 'CosFace', 'SphereFace', 'Am_softmax']
>         LOSS_NAME = 'Focal', # support: ['Focal', 'Softmax']
> 
>         INPUT_SIZE = [112, 112], # support: [112, 112] and [224, 224]
>         RGB_MEAN = [0.5, 0.5, 0.5], # for normalize inputs to [-1, 1]
>         RGB_STD = [0.5, 0.5, 0.5],
>         EMBEDDING_SIZE = 512, # feature dimension
>         BATCH_SIZE = 512,
>         DROP_LAST = True, # whether drop the last batch to ensure consistent batch_norm statistics
>         LR = 0.1, # initial LR
>         NUM_EPOCH = 125, # total epoch number (use the firt 1/25 epochs to warm up)
>         WEIGHT_DECAY = 5e-4, # do not apply to batch_norm parameters
>         MOMENTUM = 0.9,
>         STAGES = [35, 65, 95], # epoch stages to decay learning rate
> 
>         DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu"),
>         MULTI_GPU = True, # flag to use multiple GPUs; if you choose to train with single GPU, you should first run "export CUDA_VISILE_DEVICES=device_id" to specify the GPU card you want to use
>         GPU_ID = [0, 1, 2, 3], # specify your GPU ids
>         PIN_MEMORY = True,
>         NUM_WORKERS = 0,
> ),
> }
> ```
> 
> than i ran python train.py I was getting this error
> 
> ```
>  ============================================================
> Overall Configurations:
> {'SEED': 1337, 'DATA_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data', 'MODEL_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/model', 'LOG_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/log', 'BACKBONE_RESUME_ROOT': './', 'HEAD_RESUME_ROOT': './', 'BACKBONE_NAME': 'IR_SE_50', 'HEAD_NAME': 'ArcFace', 'LOSS_NAME': 'Focal', 'INPUT_SIZE': [112, 112], 'RGB_MEAN': [0.5, 0.5, 0.5], 'RGB_STD': [0.5, 0.5, 0.5], 'EMBEDDING_SIZE': 512, 'BATCH_SIZE': 512, 'DROP_LAST': True, 'LR': 0.1, 'NUM_EPOCH': 125, 'WEIGHT_DECAY': 0.0005, 'MOMENTUM': 0.9, 'STAGES': [35, 65, 95], 'DEVICE': device(type='cuda', index=0), 'MULTI_GPU': True, 'GPU_ID': [0, 1, 2, 3], 'PIN_MEMORY': True, 'NUM_WORKERS': 0}
> ============================================================
> Traceback (most recent call last):
>   File "train.py", line 70, in <module>
>     dataset_train = datasets.ImageFolder(os.path.join(DATA_ROOT, 'imgs'), train_transform)
>   File "/home/mustafa/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 178, in __init__
>     target_transform=target_transform)
>   File "/home/mustafa/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 75, in __init__
>     classes, class_to_idx = find_classes(root)
>   File "/home/mustafa/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 23, in find_classes
>     classes = [d for d in os.listdir(dir) if os.path.isdir(os.path.join(dir, d))]
> FileNotFoundError: [Errno 2] No such file or directory: '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data/imgs'
> ```
> 
> Solved this by changing ` dataset_train = datasets.ImageFolder(os.path.join(DATA_ROOT, 'imgs'), train_transform)` to ` dataset_train = datasets.ImageFolder(os.path.join(DATA_ROOT, 'train'), train_transform)`
> 
> but again a new error dancing_men
> 
> ```
> ============================================================
> Overall Configurations:
> {'SEED': 1337, 'DATA_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data', 'MODEL_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/model', 'LOG_ROOT': '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/buffer/log', 'BACKBONE_RESUME_ROOT': './', 'HEAD_RESUME_ROOT': './', 'BACKBONE_NAME': 'IR_SE_50', 'HEAD_NAME': 'ArcFace', 'LOSS_NAME': 'Focal', 'INPUT_SIZE': [112, 112], 'RGB_MEAN': [0.5, 0.5, 0.5], 'RGB_STD': [0.5, 0.5, 0.5], 'EMBEDDING_SIZE': 512, 'BATCH_SIZE': 512, 'DROP_LAST': True, 'LR': 0.1, 'NUM_EPOCH': 125, 'WEIGHT_DECAY': 0.0005, 'MOMENTUM': 0.9, 'STAGES': [35, 65, 95], 'DEVICE': device(type='cuda', index=0), 'MULTI_GPU': True, 'GPU_ID': [0, 1, 2, 3], 'PIN_MEMORY': True, 'NUM_WORKERS': 0}
> ============================================================
> /home/mustafa/anaconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py:115: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
>   self.weights = torch.tensor(weights, dtype=torch.double)
> Number of Training Classes: 5749
> Traceback (most recent call last):
>   File "train.py", line 85, in <module>
>     lfw, cfp_ff, cfp_fp, agedb, calfw, cplfw, vgg2_fp, lfw_issame, cfp_ff_issame, cfp_fp_issame, agedb_issame, calfw_issame, cplfw_issame, vgg2_fp_issame = get_val_data(DATA_ROOT)
>   File "/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/util/utils.py", line 63, in get_val_data
>     lfw, lfw_issame = get_val_pair(data_path, 'lfw')
>   File "/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/util/utils.py", line 56, in get_val_pair
>     carray = bcolz.carray(rootdir = os.path.join(path, name), mode = 'r')
>   File "bcolz/carray_ext.pyx", line 1067, in bcolz.carray_ext.carray.__cinit__
>   File "bcolz/carray_ext.pyx", line 1369, in bcolz.carray_ext.carray._read_meta
> FileNotFoundError: [Errno 2] No such file or directory: '/media/mustafa/ubuntu_backup/face/face.evoLVe.PyTorch/data/lfw/meta/sizes'
> ```
> 
> I am using ifw data base and my train folde is just rename of ifw to train can you tell me what i am doing wrong confused

any updates here, i also got this error, how to prepare "/meta/sizes" for the training dataset? Thanks
