### ISSUE TITLE
FaceAlignment not working

### ISSUE THREAD

**Issue by JerryHanZD** [ZhaoJ9014/face.evoLVe.PyTorch#70]
Thanks for the code! I met a little problem that the detect_faces(img) method doesn't seem to work.  When I run the face_align.py, the image can't be sent to detector method, and I can't find the the source problem... Does anyone have the same problem? Thx!

**Comment by JerryHanZD** [comment]
The exception says "<class 'FileNotFoundError'> face_align.py 40", where the 40th line of code is 
_, landmarks = detect_faces(img)

Can anyone help me with this? 

> Thanks for the code! I met a little problem that the detect_faces(img) method doesn't seem to work. When I run the face_align.py, the image can't be sent to detector method, and I can't find the the source problem... Does anyone have the same problem? Thx!

**Comment by ZhaoJ9014** [comment]
> The exception says "<class 'FileNotFoundError'> face_align.py 40", where the 40th line of code is
> _, landmarks = detect_faces(img)
> 
> Can anyone help me with this?
> 
> > Thanks for the code! I met a little problem that the detect_faces(img) method doesn't seem to work. When I run the face_align.py, the image can't be sent to detector method, and I can't find the the source problem... Does anyone have the same problem? Thx!

Hi, it seems that you did not successfully read the image data and pass to the function of "detect_faces". You can check whether your code on data loading. Hope this helps:)

**Comment by JerryHanZD** [comment]
> > The exception says "<class 'FileNotFoundError'> face_align.py 40", where the 40th line of code is
> > _, landmarks = detect_faces(img)
> > Can anyone help me with this?
> > > Thanks for the code! I met a little problem that the detect_faces(img) method doesn't seem to work. When I run the face_align.py, the image can't be sent to detector method, and I can't find the the source problem... Does anyone have the same problem? Thx!
> 
> Hi, it seems that you did not successfully read the image data and pass to the function of "detect_faces". You can check whether your code on data loading. Hope this helps:)

Thank you soooo much for replying!! Yeah, I thought about the loading problem but I added print(img) before sending img to detector, and I can get the image infos in the console, so I think it's not a loading problem (maybe)?
