### ISSUE TITLE
ImageFolder in train.py

### ISSUE THREAD

**Issue by JerryHanZD** [ZhaoJ9014/face.evoLVe.PyTorch#73]
Hi, I got another question here.... When I try to load the dataset_train, the datasets.ImageFolder(os.path.join(DATA_ROOT, 'imgs'), train_transform) doesn't seem to find the correct place. 
The error indicates that 'No such file or directory'. I try to use 'for subfolders in tqdm' to get the subfolders and add to the directory, it still says can't find any files in the subfolders.
And also just to be clear, DATA_ROOT should be the upper directory of training data? And could anyone help explain what 'imgs' here means?
Thanks!!!!!!

**Comment by ZhaoJ9014** [comment]
> Hi, I got another question here.... When I try to load the dataset_train, the datasets.ImageFolder(os.path.join(DATA_ROOT, 'imgs'), train_transform) doesn't seem to find the correct place.
> The error indicates that 'No such file or directory'. I try to use 'for subfolders in tqdm' to get the subfolders and add to the directory, it still says can't find any files in the subfolders.
> And also just to be clear, DATA_ROOT should be the upper directory of training data? And could anyone help explain what 'imgs' here means?
> Thanks!!!!!!

Hi, os.path.join(DATA_ROOT, 'imgs') is our training data root. 'imgs' is a subfolder under DATA_ROOT. You can change it to your own data path.

**Comment by JerryHanZD** [comment]
Thank you for answering! I've tried changing the data path and I'm pretty sure the data path's correct. But it's still indicating that "FileNotFoundError: [Errno 2] No such file or directory: '/home/jerryhan/Work/FaceRecognition/face.evoLVe.PyTorch/training/data/lfw/meta/sizes'". The LWF dataset I downloaded only contains images and there's no other meta infos in the folder. Did I miss any data processing stuff in previous steps? 
Thx!

**Comment by salihinsaealal** [comment]
> Thank you for answering! I've tried changing the data path and I'm pretty sure the data path's correct. But it's still indicating that "FileNotFoundError: [Errno 2] No such file or directory: '/home/jerryhan/Work/FaceRecognition/face.evoLVe.PyTorch/training/data/lfw/meta/sizes'". The LWF dataset I downloaded only contains images and there's no other meta infos in the folder. Did I miss any data processing stuff in previous steps?
> Thx!

Hi, have you got the solution?
