### ISSUE TITLE
Unable to download IR-152 pretrained model from baidu-drive 

### ISSUE THREAD

**Issue by pp3993** [ZhaoJ9014/face.evoLVe.PyTorch#75]
The content you downloaded contains the folder, please use the Baidu network disk client to download.
Install the latest version of the network disk client
A new version of the client has been installed and still cannot be downloaded for reasons.

**Comment by pp3993** [comment]
Please upload in google drive also.

**Comment by ZhaoJ9014** [comment]
> Please upload in google drive also.

Hi, since we have reached the upper limit of Google Drive, we change to Baidu Drive instead, could you download the Baidu Drive app and download the model via it? which is very simple:)
