### ISSUE TITLE
Difference between Resnet50 and IR_50

### ISSUE THREAD

**Issue by Source82** [ZhaoJ9014/face.evoLVe.PyTorch#76]
Hi,
Pardon my rather simplistic question, what is the difference between Resnet50 and IR_50  backbones, I noticed they both cite the same paper.

**Comment by ZhaoJ9014** [comment]
> Hi,
> Pardon my rather simplistic question, what is the difference between Resnet50 and IR_50 backbones, I noticed they both cite the same paper.

Hi, thank you for your question. IR_50 is an improved version of the vanilla ResNet-50. You can check the ArcFace paper:)
