### ISSUE TITLE
Face Recognition- simple API example

### ISSUE THREAD

**Issue by yoniker** [ZhaoJ9014/face.evoLVe.PyTorch#77]
Hi! :)

So, I'm looking for an already trained model for face recognition.
Your github readme jumps straight from how to do face alignment with your repo,
to how to train/validate. I'm not interested in training a model,but just use it :)
Can you add to your README a simple,user-friendly example of how to use the trained models to do face recognition,get the embeddings,compare between faces etc.?
I'm sure other people will appreciate that as well :)

Thanks in advnace guys,great work!

**Comment by ZhaoJ9014** [comment]
> Hi! :)
> 
> So, I'm looking for an already trained model for face recognition.
> Your github readme jumps straight from how to do face alignment with your repo,
> to how to train/validate. I'm not interested in training a model,but just use it :)
> Can you add to your README a simple,user-friendly example of how to use the trained models to do face recognition,get the embeddings,compare between faces etc.?
> I'm sure other people will appreciate that as well :)
> 
> Thanks in advnace guys,great work!

Hi, actually we have provided the feature extraction API (extract features from pre-trained models) ./util/extract_feature_v1.py (implemented with PyTorch build-in functions) and ./util/extract_feature_v2.py (implemented with OpenCV). To compute the distance, you can simply refer to the "perform_val" function in ./util/utils.py :)

**Comment by ZeeshanHussainKh** [comment]
Hi @ZhaoJ9014  , I was  wondering on how we can generate carray and issame for my own dataset that you use in perform_eval function in utils.py ?

I need to perform evaluation of my model on my own dataset of facescrub images.
