### ISSUE TITLE
Reduced accuracy after saving and loading model

### ISSUE THREAD

**Issue by Source82** [ZhaoJ9014/face.evoLVe.PyTorch#78]
I had an accuracy of 99.7% on LFW after saving the backbone and head and reloading them I notice ~2% drop in accuracy on test data. I have tried this again and again on other check points it seems consistent. Could this be due to a bug in the way the checkpoints are saved?

**Comment by ZhaoJ9014** [comment]
> I had an accuracy of 99.7% on LFW after saving the backbone and head and reloading them I notice ~2% drop in accuracy on test data. I have tried this again and again on other check points it seems consistent. Could this be due to a bug in the way the checkpoints are saved?

Hi, which checkpoint did you use for evaluation on LFW? For IR-152, we found the checkpoint of epoch_37 achieves the best performance, which is reported in the repo. We have released 3 checkpoints in the folder for IR-152 in total.

**Comment by Source82** [comment]
I was training with IR_SE_50 backbone
