### ISSUE TITLE
face alignment lfw

### ISSUE THREAD

**Issue by jeroneandrews** [ZhaoJ9014/face.evoLVe.PyTorch#79]
If I perform face alignment using MTCNN on the lfw images, then I end up with fewer than 6000 pairs due to MTCNN being unable to detect/align each one of the lfw images.

How come when I download your LFW (Align_112x112) from Google drive I see that there are 6000 pairs? How did you get MTCNN to successfully align each of the LFW images?

Thanks.

**Comment by ZhaoJ9014** [comment]
> If I perform face alignment using MTCNN on the lfw images, then I end up with fewer than 6000 pairs due to MTCNN being unable to detect/align each one of the lfw images.
> 
> How come when I download your LFW (Align_112x112) from Google drive I see that there are 6000 pairs? How did you get MTCNN to successfully align each of the LFW images?
> 
> Thanks.

Hi, did you perform face alignment on LFW raw data?

**Comment by jeroneandrews** [comment]
@ZhaoJ9014  Yes, on the raw data.

**Comment by ZhaoJ9014** [comment]
> @ZhaoJ9014 Yes, on the raw data.

So strange..Well, you can adjust the hyper-parameters and see.

**Comment by jeroneandrews** [comment]
@ZhaoJ9014 Hi, I just ended up using the lfw data you uploaded to google drive instead. Thanks for uploading the datasets, it's been very helpful.

However, you store the lfw data in BGR order but train on RGB data? Was this a mistake?

**Comment by msedebrahimi** [comment]
> > @ZhaoJ9014 Yes, on the raw data.
> 
> So strange..Well, you can adjust the hyper-parameters and see.

Can you release the hyperparameter that you used? I am trying to align CFP but I could not reproduce the exact results of yours
