### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by DecentMakeover** [ZhaoJ9014/face.evoLVe.PyTorch#8]
Hi 

Thanks for sharing your work,

I don't  have resources to train any models, but is there only inference code available to test on my images?

Thanks

**Comment by ZhaoJ9014** [comment]
Thank you for your question. For inference on your own data, you can refer to Line 85 and 226-245 of train.py as an example. If you load your data from a folder, you can refer to Line 61-70 as an example.
