### ISSUE TITLE
MS-Celeb Low Shot dataset links!

### ISSUE THREAD

**Issue by aplusc98** [ZhaoJ9014/face.evoLVe.PyTorch#80]
Hey,

All the links for MS celeb Low shot links in the previous issues have expired could you please post the link for the MS-celeb Low Shot dataset please!

**Comment by ZhaoJ9014** [comment]
> Hey,
> 
> All the links for MS celeb Low shot links in the previous issues have expired could you please post the link for the MS-celeb Low Shot dataset please!

Hi, we have checked the links and did not find any issue. Please have a check again:)
