### ISSUE TITLE
CASIA-SURF zip password

### ISSUE THREAD

**Issue by kormalev** [ZhaoJ9014/face.evoLVe.PyTorch#81]
Could you please share the password(s) for train.zip and valid.zip archives inside CASIA-SURF-20190715T161935Z-001.zip

**Comment by kormalev** [comment]
train.zip:casia-cbsr-train-29266
valid.zip:casia-cbsr-valid-9608

**Comment by AnhNguyen1805** [comment]
Could someone share the CASIA-SURF dataset to another location please?
I cannot access or register a user in baidu to download dataset
Thank you,
