### ISSUE TITLE
Model Zoo IR-152 download link is broken

### ISSUE THREAD

**Issue by fjordyo0707** [ZhaoJ9014/face.evoLVe.PyTorch#83]
Hi,
In model zoo, the download link of IR-152 is broken. Also, is it possible upload the files to google drive?
Thank you!

**Comment by fjordyo0707** [comment]
It seems that I can’t use Baidu drive in my region.

**Comment by ZhaoJ9014** [comment]
Hi, we have checked the baidu drive link and pw, and we did not find any problem. Please check again. Currently, our google drive has reached its upper limit, we will try to upload the model to google drive in near future.
