### ISSUE TITLE
IR-152 wrong password

### ISSUE THREAD

**Issue by bobiblazeski** [ZhaoJ9014/face.evoLVe.PyTorch#85]
I'm unable to download IR-152 google auto translate says wrong code used y6ya as written
![Screenshot from 2019-07-31 14-37-41](https://user-images.githubusercontent.com/2140890/62212359-d5865280-b3a0-11e9-92b7-94bf65a079e0.png)
I'm using chrome on ubuntu 18.04

Adding option for any english service such as google drive, onedrive, dropbox etc would be highly appreciated. If download quota for the user is already used, anyone could link it to their own account and download. Approach used in StyleGan  models. https://www.geekrar.com/fix-bypass-google-drive-download-limit-error/

**Comment by fjordyo0707** [comment]
I am facing the same problem, and I find out that you need to download them through vpn with China domain, then you have to register a Baidu account, which need a China phone number.

I successfully download them last night. If you need the models, I can upload them to my google drive and send the link to you privately.

**Comment by bobiblazeski** [comment]
@fjordyo0707  Would be very grateful if you could send me the model link to slobodan.blazeski@gmail.com

**Comment by ZhaoJ9014** [comment]
> I'm unable to download IR-152 google auto translate says wrong code used y6ya as written
> ![Screenshot from 2019-07-31 14-37-41](https://user-images.githubusercontent.com/2140890/62212359-d5865280-b3a0-11e9-92b7-94bf65a079e0.png)
> I'm using chrome on ubuntu 18.04
> 
> Adding option for any english service such as google drive, onedrive, dropbox etc would be highly appreciated. If download quota for the user is already used, anyone could link it to their own account and download. Approach used in StyleGan models. https://www.geekrar.com/fix-bypass-google-drive-download-limit-error/

Hi, we have checked the baidu drive link and password, and we did not find any problem. Please check again:) Our google drive has reached its upper limit, we will try to upload the model to google drive in near future.
