### ISSUE TITLE
train.py产生的模型和align目录下的内容有什么关系？

### ISSUE THREAD

**Issue by cloudsurging** [ZhaoJ9014/face.evoLVe.PyTorch#87]
train.py产生的模型和align目录下的内容有什么关系？

**Comment by ZhaoJ9014** [comment]
> train.py产生的模型和align目录下的内容有什么关系？

Hi, the folder "align" is for face detection and alignment as pre-processing before recognition. The model learned by train.py is the final trained the model on large-scale data for recognizing faces in the wild.
