### ISSUE TITLE
How to get AgeDB-30 verification pairs?

### ISSUE THREAD

**Issue by MBXH** [ZhaoJ9014/face.evoLVe.PyTorch#88]
How to get AgeDB-30 verification pairs?
I read the paper of AgeDB, but I did not find a description of the verification pair in this dataset. Does this verification pair have an official division, or is it randomly divided according to the rules in the paper?

**Comment by ZhaoJ9014** [comment]
> How to get AgeDB-30 verification pairs?
> I read the paper of AgeDB, but I did not find a description of the verification pair in this dataset. Does this verification pair have an official division, or is it randomly divided according to the rules in the paper?

Yes, the original paper also conducted age-invariant face recognition experiment on AgeDB.
