### ISSUE TITLE
CASIA-Surf

### ISSUE THREAD

**Issue by mlourencoeb** [ZhaoJ9014/face.evoLVe.PyTorch#91]
This is not really an issue.

Can someone please upload CASIA-SURF dataset to other fileshare system? I am not being able to download it, since I cannot create Baidu account.

Really appreciate it.

**Comment by kormalev** [comment]
[train.zip](https://mega.nz/#!6OpEiITJ!gfLQMkLEz5DsyMyiVSWqr5CHBaIjIX9S_Y8HN2XcPnM)
[valid.zip](https://mega.nz/#!qbpQHKgL!gYFtSA9JLjAH6HwT7zAx-ysH3Zr4-2RmTfwuK80aR0Q)

**Comment by mlourencoeb** [comment]
@kormalev thanks for providing the data.

**Comment by parthagar** [comment]
@kormalev do you have the complete dataset? The one's that you have uploaded here only has the print cut-out attack images. Thanks in anticipation.

**Comment by kormalev** [comment]
@parthagar, this is the exact same data from Baidu with passwords removed. AFAIK, it is the full original dataset distributed during the contest.

**Comment by parthagar** [comment]
@kormalev, I'm afraid that is not the case. Take a look at Section 3 of the [CASIA-SURF Paper](http://www.cbsr.ia.ac.cn/users/xiaobowang/papers/CASIA-SURF_CameraReady_Final.pdf). Anyways thanks for providing this data, if you come across the complete version or if you have OULU-NPU, SiW-M please do tell me, I need them.

**Comment by kormalev** [comment]
@parthagar, the paper describes 6 attack modes, all of them being print cut-out attacks with variations in what is being cut out and whether the paper is bent or not.
As for SiW-M, you can request it for research purposes through the authors' website.

**Comment by mike07026** [comment]
@parthagar Do you have SiW or SiW-M dataset? I need them too~

**Comment by Morceguito** [comment]
Does anyone have Replay-attack, oulu-npu access? I am working on my thesis and would be appreciated

**Comment by Morceguito** [comment]
@kormalev do you have replay-attack or oulu-npu dataset? I am working on my thesis and i need it asap
