### ISSUE TITLE
Missing key(s) in state_dict: "weight".

### ISSUE THREAD

**Issue by bleakie** [ZhaoJ9014/face.evoLVe.PyTorch#95]
This error occurred when I introduced the pre training model. What's wrong with it?
Loading Backbone Checkpoint './checkpoint/ms1m_ir50/backbone_ir50_ms1m_epoch63.pth'
Loading Head Checkpoint './checkpoint/ms1m_ir50/backbone_ir50_ms1m_epoch63.pth'
Traceback (most recent call last):
  File "/home/sai/YANG/face_recognition/face.evoLVe.PyTorch/train.py", line 142, in <module>
    HEAD.load_state_dict(torch.load(HEAD_RESUME_ROOT))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ArcFace:
	Missing key(s) in state_dict: "weight". 
	Unexpected key(s) in state_dict: "input_layer.0.weight", "input_layer.1.weight", "input_layer.1.bias", "input_layer.1.running_mean", "input_layer.1.running_var", "inp

**Comment by anguoyang** [comment]
hi @bleakie , have solved the problem?
