### ISSUE TITLE
CASIA-SURF‘s unzipping password

### ISSUE THREAD

**Issue by WH2016** [ZhaoJ9014/face.evoLVe.PyTorch#97]
Hi, I have downloaded the CASIA-SURF data from the given link. But when I unzip the file, it needs unzipping password. Can you please provide the password? Thanks!

**Comment by maoyichun** [comment]
@WH2016 did you get the password?Can you please provide the password? Thanks!

**Comment by WH2016** [comment]
@maoyichun 
train.zip:casia-cbsr-train-29266
valid.zip:casia-cbsr-valid-9608

**Comment by tloki** [comment]
Does anybody know the unzip password for CASIA-CeFA (new/extended/multi-ethnicity version of CASIA-SURF) train.zip and dev.zip ?

for test.zip: casia-cefa-test-572121-usd89f

They are available to download here:
Google Drive: https://drive.google.com/drive/folders/1i95Pnk8BEIpbyCt-UZFHhtxpkLpC5Gey?usp=sharing 

Baidu: https://pan.baidu.com/s/1Wquwr0fJArR0lydrEHlAsA#list/path=%2F

**Comment by vocong25** [comment]
@tloki  had you have the passwords for train and dev dataset?

**Comment by tloki** [comment]
I did not get it yet... Do you know the passwords?

**Comment by vocong25** [comment]
@tloki I don't have it for now. So how did you get those links?

**Comment by vocong25** [comment]
@tloki I cannot download train and dev set from baidu. Can you help me?

**Comment by tloki** [comment]
I find editing a comment asking where I got the link first, and requiring assistance after wise, to be suspicious at least. The links, as well as the password is made public. I was not a part of CASIA-CeFA competition nor do I know anybody or am affiliated with anybody that is.

But hey, if anybody else knows the password/s, please let us know.

**Comment by smartwell** [comment]
> I find editing (edit: actually, you have deleted your previous comment) a comment asking where I got the link first, and requiring assistance after wise, to be suspicious at least. The links, as well as the password is made public. I was not a part of CASIA-CeFA competition nor do I know anybody or am affiliated with anybody that is.
> 
> But hey, if anybody else knows the password/s, please let us know.

hey, now do you know the password?

**Comment by tloki** [comment]
Anybody?

**Comment by JRZNBU** [comment]
do you know the password of train.zip?

**Comment by JRZNBU** [comment]
> 
> 
> Does anybody know the unzip password for CASIA-CeFA (new/extended/multi-ethnicity version of CASIA-SURF) train.zip and dev.zip ?
> 
> for test.zip: casia-cefa-test-572121-usd89f
> 
> They are available to download here:
> Google Drive: https://drive.google.com/drive/folders/1i95Pnk8BEIpbyCt-UZFHhtxpkLpC5Gey?usp=sharing
> 
> Baidu: https://pan.baidu.com/s/1Wquwr0fJArR0lydrEHlAsA#list/path=%2F

dou you know the train-set password?

**Comment by cuevas1208** [comment]
> > Does anybody know the unzip password for CASIA-CeFA (new/extended/multi-ethnicity version of CASIA-SURF) train.zip and dev.zip ?
> > for test.zip: casia-cefa-test-572121-usd89f
> > They are available to download here:
> > Google Drive: https://drive.google.com/drive/folders/1i95Pnk8BEIpbyCt-UZFHhtxpkLpC5Gey?usp=sharing
> > Baidu: https://pan.baidu.com/s/1Wquwr0fJArR0lydrEHlAsA#list/path=%2F
> 
> dou you know the train-set password?

casia-cbsr-train-29266 does not work, what is the password?

**Comment by petercheng85** [comment]
> @maoyichun
> train.zip:casia-cbsr-train-29266
> valid.zip:casia-cbsr-valid-9608

do you know password for testing set? thank you!

**Comment by sivi-shahab** [comment]
Please give me link to download CASIA-Surf dataset?

**Comment by sfxcokpe** [comment]
> Please give me link to download CASIA-Surf dataset?

Hello. @sivi-shahab please were you able to download the dataset? and if you were able to download it, can you share the link?
